[workspace]
resolver = "2"
members = [
    "saiga",
    "saiga_backend",
    "saiga_vte",
    "saiga_frontend",
    "saiga_input",
    "saiga_macros", "saiga_bench",
]

# https://deterministic.space/high-performance-rust.html
[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
