[package]
name = "saiga_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
saiga_vte = { path = "../saiga_vte" }
unicode-width = "0.2.0"
nix = { version = "0.29.0", features = ["term", "process", "fs"] }
