[package]
name = "saiga_frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
saiga_backend = { path = "../saiga_backend" }
saiga_vte = { path = "../saiga_vte" }
wgpu = "22.1.0"
winit = "0.30.5"
log = "0.4.22"
