[package]
name = "saiga_input"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.8.0"
saiga_macros = { path = "../saiga_macros" }
winit = { version = "0.30.9", optional = true }

[features]
winit = ["dep:winit"]
