[package]
name = "saiga"
version = "0.1.0"
edition = "2021"

[dependencies]
saiga_frontend = { path = "../saiga_frontend" }
saiga_backend = { path = "../saiga_backend" }
saiga_vte = { path = "../saiga_vte" }
